version: '3'

services:
  app:
    container_name: unittest
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python3 -m unittest'
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
